In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('numpy-array-operations-f4abd')
jovian.set_colab_id('1slyBUzbiRsCkdx7RizZ-UN6B7ah01ihG')

     |████████████████████████████████| 68 kB 2.6 MB/s 


> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>



### Introduction
Write a short introduction about Numpy and list the chosen functions. 

- np.concatenate
- np.reshape
- np.arange
- np.linspace
- np.round

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [16]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.reshape
function3 = np.arange
function4 = np.linspace
function5 = np.round

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [18]:
# Example 1 - working (change this)
#Concatenation of two 2-dimentaional array of size (arr1=(2,2) & arr2= (2,3))  in arr1 with column-wise.
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Concatenation of two 2-dimentaional array of size (arr1=(2,2) & arr2= (2,3))  in arr1 with column-wise.It will execute normally because arr1 and arr2 has same size of row.and their is No make any requiirement of column size must be same.**bold text**

In [19]:
# Example 2 - working
# Concatenation of two 2-dimentaional array of size (arr1=(2,2) & arr2= (2,3))  in arr1 with row-wise.

### Concatenation of two 2-dimentaional array of size (arr1=(2,2) & arr2= (2,3))  in arr1 with row-wise.**bold text**

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
# it will gives valueError.Because different size of column.column size must be same as we try to conatenate arrays in row-wise.arr1 has column size 2 and arr2 has column is 3.we can solve problem this in 2 ways 1.making increase size in row of arr1 or 2.making decrease size in row of arr2
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: ignored

**It gives valueError because different size of column.column size must be same as we try to conatenate arrays in row-wise.arr1 has column size 2 and arr2 has column is 3.we can solve problem this in 2 ways 1.making increase size in row of arr1 or 2.making decrease size in row of arr2.**

### We can use concatenate function to addition of 2 arrays of different size.

In [21]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'

##Function 2 - np.reshape


1.Matrix multiplication of two arrays of size 1-Dimentaional and 2-Diamentional and then concatenation followed by reshaping array in column-wise added in a and perform mean operation on a also attached in columnwise.

In [22]:
# Example 1 - working
a = np.array([[1.5,2.5,3.5],[4.5,5.6,7.8],[7.9,8.9,4.6]])
b = np.array([10.4,4.6,7.9])
c = a @ b
d= np.concatenate((a,c.reshape(3,1)),axis=1)
final= np.mean(((d)),axis=1)
print(np.concatenate((a,c.reshape(3,1),final.reshape(3,1)),axis =1))

[[  1.5      2.5      3.5     54.75    15.5625]
 [  4.5      5.6      7.8    134.18    38.02  ]
 [  7.9      8.9      4.6    159.44    45.21  ]]


Take two arrays of size 1-diam. and 2-diam.array size(1,3) and (3,3).Perform matrix mutiplication.Then array a and c concatenated with reshape of c size=(3,1) and in array a add in column-wise.then find mean of array d with column-wise.finally we have concatenate array a, c and final in column-wise.

In [23]:
# Example 2 - working
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b= np.array([100,200,300])
c=np.matmul(a,b)
d= np.concatenate((a,c.reshape(3,1)),axis=1)
final= np.sum(((d)),axis=1)
print(np.concatenate((a,c.reshape(3,1),final.reshape(3,1)),axis =1))

[[   10    20    30 14000 14060]
 [   40    50    60 32000 32150]
 [   70    80    90 50000 50240]]


Take two arrays of size 1-diam. and 2-diam.array size(1,3) and (3,3).Perform matrix mutiplication.Then array a and c concatenated with reshape of c size=(3,1) and in array a add in column-wise.then find sum of array d with column-wise.finally we have concatenate array a, c and final in column-wise.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.round([[1.5,2.5,3.5],[4.5,5.6,7.8],[7.9,8.9,4.6]])
b = np.round([10.4,4.6,7.9])
c = a @ b
print(np.concatenate((a,c),axis=1))

ValueError: ignored

Explanation about example (why it breaks and how to fix it): <br>
Take two arrays of size 1-diam. and 2-diam.array size(1,3) and (3,3) of float datatype.Perform matrix mutiplication.Then array a and c concatenated with reshape as default,get valueError.we can fix it by reshape(3,1) of c array then we can perform concatenation in column-wise.

Some closing comments about when to use this function: <br>
We can use reshape function to adjust an array in such way that we can perform concatenation on it.

In [25]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'

## ## Function 3 - np.reshape


Find range values between 2 and 23 with gap of 4 values and perform reshape operation on a array to get size (2,3).

In [26]:
# Example 1 - working
a= np.arange(2,23,4).reshape(2,3)
print(a)

[[ 2  6 10]
 [14 18 22]]


Finding range of 4 values between 2 and 20 values and then perform reshape operation on a array to get size (2,2).

In [27]:
# Example 2 - working
b= np.linspace(2,20,4).reshape(2,2)
print(b)

[[ 2.  8.]
 [14. 20.]]


In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
c= np.arange(16).reshape(4,3)
d=np.transpose(c)
print(d)

Explanation about example (why it breaks and how to fix it): <br>
A range of numbers from o to 15 and perfrom reshape operation to get proper array. but because of size(4,3).we get valueError.we can solve this problem by using size(4,4).

In [28]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'

##Function 3 - np.arange

Find range of values from 0 to 24 and split in 4 rows and perform operation in column-wise.then perfom conactenation.

In [29]:
# Example 1 - working
a= np.arange(24)
b= np.split(a,4)
c= np.sum((b),axis=1)
print(np.concatenate((b,c.reshape(4,1)),axis=1))

[[  0   1   2   3   4   5  15]
 [  6   7   8   9  10  11  51]
 [ 12  13  14  15  16  17  87]
 [ 18  19  20  21  22  23 123]]


Taking range of 24 values then split in 4 rows and then perform sum operation in column-wise. Finally concatenate sum values and range of 24 values in column-wise.

In [30]:
# Example 2 - working
a= np.arange(16).reshape(4,4)
b=np.transpose(a)
c = np.mean((b),axis=0)
d= np.concatenate((b,c.reshape(1,4)),axis=0)
print(d)

[[ 0.   4.   8.  12. ]
 [ 1.   5.   9.  13. ]
 [ 2.   6.  10.  14. ]
 [ 3.   7.  11.  15. ]
 [ 1.5  5.5  9.5 13.5]]


In [31]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.arange(2,36).reshape(4,3)
b = np.sum((a),axis=1)
c= np.concatenate((a,b.reshape(4,1)),axis=1)
print(c)

ValueError: ignored

Explanation about example (why it breaks and how to fix it): <br>
In arange function we must have to specify 3 parameters  as minimum value, maximum value and gap in between values if we forgot to specify any values we get ValueError. It can be eliminated by specifying 3 parameters.

In [32]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'

## Function 5 - np.linspace

Linspace is use to find values as per given range

In [ ]:
# Example 1 - working
a = np.linspace(0,40,12).reshape(4,3)
b= np.max((a),axis=0)
print(np.concatenate((a,b.reshape(1,3)),axis= 0))

Explanation about example

In [33]:
# Example 2 - working
a=np.linspace(0,50,12).reshape(4,3)
b= np.min((a),axis =1)
c= np.concatenate((a,b.reshape(4,1)),axis=1)
print(c)

[[ 0.          4.54545455  9.09090909  0.        ]
 [13.63636364 18.18181818 22.72727273 13.63636364]
 [27.27272727 31.81818182 36.36363636 27.27272727]
 [40.90909091 45.45454545 50.         40.90909091]]


In [34]:
# Example 3 - breaking (to illustrate when it breaks)
a= np.linspace(0,100,10).reshape(4,3)
b= np.std((a),axis =1)
c= np.concatenate((a,b.reshape(4,1)),axis=1)
print(c)

ValueError: ignored

Explanation about example (why it breaks and how to fix it): <br>
In linespace function, we get an valueErrorbecause as we put improper linespace and reshape size.To solve this problem  we must put proper parameters in linespace and it must match with reshape size.

In [35]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'

In [36]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/akshay270802/numpy-array-operations


'https://jovian.ai/akshay270802/numpy-array-operations'